<?php

$title = 'Add new contact';
$this->headTitle($title);

?>
<h1><?php echo $this->escapeHtml($title);?></h1>

<?php

$form->setAttribute('action', $this->url('contact', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);

echo $this->formHidden($form->get('id'));
?>
<div class="container">
	
	<div class="row">
		<div class="col-lg-7">
			<div class="col-lg-4">
			    First name:
			</div>
			<div class="col-lg-8">
				<?php echo $this->formRow($form->get('first_name')); ?>
			</div>
		</div>
	</div><br/>

	<div class="row">
		<div class="col-lg-7">
			<div class="col-lg-4">
			    Last name:
			</div>
			<div class="col-lg-8">
				<?php echo $this->formRow($form->get('last_name')); ?>
			</div>
		</div>
	</div><br/>

	<div class="row">
		<div class="col-lg-7">
			<div class="col-lg-4">
			    Phone number:
			</div>
			<div class="col-lg-8">
				<?php echo $this->formRow($form->get('phone_number')); ?>
			</div>
		</div>
	</div><br/>

	<div class="row">
		<div class="col-lg-7">
			<div class="col-lg-4">
			    Address:
			</div>
			<div class="col-lg-8">
				<?php echo $this->formRow($form->get('address')); ?>
			</div>
		</div>
	</div><br/>

	<div class="row">
		<div class="col-lg-7">
			<div class="col-lg-4">
			    Comment:
			</div>
			<div class="col-lg-8">
				<?php echo $this->formRow($form->get('comment')); ?>
			</div>
		</div>
	</div><br/>

	<div class="row">
		<div class="col-lg-7">
			<div class="col-lg-4">
			    <?php echo $this->formSubmit($form->get('submit')); ?>
			</div>
			<div class="col-lg-8">
				
			</div>
		</div>
	</div><br/>

</div>

<?php
echo $this->form()->closeTag();
?>



