<?php
$title = "Delete contact";
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete "<?php echo $this->escapeHtml($contact->first_name);?>" ?
   </p>
<?php
$url = $this->url('contact' , array(
				'action' => 'delete',
				'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">

	<div class = "container">
		<input type = "hidden" name="id" value="<?php echo (int) $contact->id; ?>" />
			<div class="row">
				<div class="col-lg-2">
					<input class="btn btn-primary" type = "submit" name="del" value="Yes" /> 
				</div>
				<div class="col-lg-2">
					<input class="btn btn-danger" type = "submit" name="del" value="No" /> 
				</div>
			</div>
	</div>

</form>